spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productTracking
    username: postgres
    password: postgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL82Dialect
      format_sql: true
    open-in-view: false
